# How to define an inventory
# https://docs.ansible.com/ansible/latest/network/getting_started/first_inventory.html

---
all:
  children:
    network:
      children:
        iosxe_routers:
          hosts:
            spine1-20.11:
              ansible_host: 10.10.20.11
            spine2-20.12:
              ansible_host: 10.10.20.12
            leaf1-20.21:
              ansible_host: 10.10.20.21
            leaf2-20.22:
              ansible_host: 10.10.20.22
            leaf3-20.23:
              ansible_host: 10.10.20.23
    clients:
      children:
        linux_hosts:
          hosts:
            host1-20.31:
              ansible_host: 10.10.20.31
            host2-20.32:
              ansible_host: 10.10.20.32
            host3-20.33:
              ansible_host: 10.10.20.33
