# How to define an inventory
# https://docs.ansible.com/ansible/latest/network/getting_started/first_inventory.html

---
all:
  children:
    clients:
      children:
        linux_hosts:
          hosts:
            host1-20.31:
              ansible_host: 10.10.20.31
            host2-20.32:
              ansible_host: 10.10.20.32
            host3-20.33:
              ansible_host: 10.10.20.33
