version: "3.8"

services:
  cml:
    image: jillesca/ansible:cml1.0
    container_name: cml
    tty: true
    volumes:
      - ./../ansible:/home
    environment:
      CML_USER: ${CML_USER}
      CML_PASSWORD: ${CML_PASSWORD}
      CML_HOST: ${CML_HOST}
      CML_LAB: ${CML_LAB}
      CML_VERIFY_CERT: ${CML_VERIFY_CERT}
  # to run only this service
  # docker-compose -f ./docker/ansible.docker-compose.yml up -d cml

  ansible:
    image: jillesca/ansible:version1.0
    container_name: ansible
    tty: true
    # If you want to build your own image
    # uncomment the lines below build
    # and add use the --build option along
    # build:
    #   context: ../
    #   target: base
    #   dockerfile: ./docker/ansible/base-ansible.dockerfile
    volumes:
      - ./../ansible:/home
      #
# For development is easiest to do changes on code locally
# and use a volume to run the changes on the containers directly
# otherwise the image has to be built everytime we do changes.
# For a pipeline, this docker-compose is not needed

# Must be executed from ROOT dir
# otherwise volumes dir must be updated
# docker-compose -f ./docker/ansible.docker-compose.yml up -d ansible

# To enter the contaienr afte it runs
# docker exec -it ansible /bin/sh
