- name: Show cisco facts
  hosts: network
  connection: ansible.builtin.network_cli
  gather_facts: no

  tasks:
    - name: Gather cisco facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Print cisco facts
      ansible.builtin.debug:
        var: ansible_facts
