# ansible-playbook cisco_cml_build.yml -vvv
- name: Build the topology
  hosts: cml
  gather_facts: no
  connection: network_cli
  vars:
    wait: "yes"
  tasks:
    - name: Create the lab
      cisco.cml.cml_lab:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: present
        file: "./files/topologies/environment-setup/setup_base_lab.yaml"
      register: results

    - name: Check to see if the Lab is there
      cisco.cml.cml_lab_facts:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
      register: cml_lab_facts
      when: wait | bool

    - name: Refresh Inventory
      meta: refresh_inventory

- name: Start Lab
  hosts: cml_hosts
  connection: local
  gather_facts: no
  tasks:
    - name: Start Lab
      cisco.cml.cml_node:
        name: "{{ inventory_hostname }}"
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: started
  tags: start

- name: Wait for Topology to BOOT
  hosts: cml
  connection: network_cli
  gather_facts: no
  tags:
    - wait
  vars:
    wait: "yes"
  tasks:
    - name: Check to see if all hosts are BOOTED
      cisco.cml.cml_lab_facts:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
      register: cml_lab_facts
      until: (states | length == 1) and (states[0] == 'BOOTED')
      retries: 40
      delay: 30
      vars:
        states: "{{ cml_lab_facts.cml_facts.nodes | default({}) | dict2items | selectattr('value.state','defined') | map(attribute='value.state') | unique | list }}"
      when: wait | bool

    - copy:
        dest: /home/lab_facts.json
        content: "{{ cml_lab_facts }}"
