# ansible-playbook cisco_cml_build.yml -vvv
- name: Build lab config
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create bootstrap lab file
      template:
        src: files/topologies/environment-setup/setup_base_lab.j2
        dest: files/topologies/environment-setup/setup_base_lab.yaml
