# ansible-playbook cisco_cml_build.yml -vvv
- name: Build the topology
  hosts: cml
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Create the lab
      cisco.cml.cml_lab:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "setup_base_lab"
        state: present
        file: "./files/topologies/environment-setup/setup_base_lab.yml"
      register: results

    - name: Refresh Inventory
      meta: refresh_inventory
    - name: Pause for 1 minute
      pause:
        minutes: 1

- name: Start Lab
  hosts: ansible_lab
  connection: local
  gather_facts: no
  tasks:
    - name: Start Lab
      cisco.cml.cml_node:
        name: "{{ inventory_hostname }}"
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "setup_base_lab"
        state: started
  tags: start
