--- 
- name: sub-element access styles 
  hosts: localhost 
  connection: local
  gather_facts: false 
  strategy: debug 
 
  vars: 
    - derp: 
        keys: 
          - c 
          - d 
 
  tasks: 
    - name: subscript style 
      ansible.builtin.debug: 
        var: derp['keys'] 
